function renderPeriodBadges(period){
 for(const [id,key] of Object.entries({revenue:'Revenue',profit:'GrossProfit',orders:'Orders','gm-kpi':'margin',yoy:'Revenue'})){
  const card=document.getElementById(id).closest('.kpi');let node=card.querySelector('.kpi-context');if(!node){node=document.createElement('div');node.className='kpi-context';card.appendChild(node)}
  const change=period.changes[key],label=period.complete?'Same period last year':`Prior coverage ${period.covered}/${period.expected} months`;
  node.innerHTML=`<span class="trend-badge ${change===null?'neutral':change<0?'down':''}">${change===null?'Not comparable':`${change<0?'↓':'↑'} ${change>=0?'+':''}${change.toFixed(1)}${key==='margin'?' pp':'%'}`}</span><span>${label}</span>`;
  node.title=`Prior period: ${period.priorFrom} through ${period.priorTo}`;
 }
}
function renderTrust(data){
 const section=document.querySelector('#quality'),meta=data.pipeline_metadata||{};
 const exact=(value,unit)=>value==null?'Not independently validated':new Intl.NumberFormat('en-US',{style:unit==='USD'?'currency':'decimal',...(unit==='USD'?{currency:'USD'}:{}),minimumFractionDigits:unit==='USD'?2:0,maximumFractionDigits:unit==='USD'?2:3}).format(value);
 section.insertAdjacentHTML('beforeend',`<article class="trust-reconciliation"><h3>Source → SQLite warehouse → published KPI</h3><p>${meta.publication_status==='APPROVED'?'Mandatory publication checks passed.':'Publication approval not available.'} Expected synthetic exceptions are identified individually; this is not a record-level quality percentage.</p><div class="table-scroll"><table><thead><tr>${['Measure','Unit','Source','SQLite fact','Published','Source / warehouse Δ','Source / published Δ','Tolerance','Result'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${(data.reconciliation||[]).map(r=>`<tr><th scope="row">${h(r.Measure)}</th><td>${h(r.Unit||'USD')}</td><td>${exact(r.RawValue,r.Unit)}</td><td>${exact(r.FactValue,r.Unit)}</td><td>${exact(r.DashboardValue,r.Unit)}</td><td>${Number(r.SourceToWarehouseVariance??r.Variance).toExponential(2)}</td><td>${Number(r.SourceToDashboardVariance??r.Variance).toExponential(2)}</td><td>${h(r.Tolerance??0.01)}</td><td>${h(r.Status)}</td></tr>`).join('')}</tbody></table></div><p>Inventory valuation: ${h(meta.valuation_policy||'See KPI dictionary')}. Missing mandatory controls or reconciliation failures block publication and retain the previous dataset.</p></article>`);
 const trust=document.createElement('aside');trust.className='architecture-teaser trust-summary';trust.innerHTML=`<div><h2>Dataset trust</h2><p>${data.data_quality?.summary?.passed_tests??0}/${data.data_quality?.summary?.total_tests??0} controls passed · ${(meta.expected_exceptions||[]).length} acknowledged synthetic exception(s) · ${data.reconciliation?.length??0} reconciled measures.</p></div><a href="#quality">Inspect controls →</a>`;document.querySelector('.architecture-teaser').before(trust);
}
function renderDecisionEvidence(data){
 const m=data.pipeline_metadata||{},f=data.business_findings||{};
 document.querySelector('#run-evidence').innerHTML=`<h3>Measured results for this publication</h3><dl class="evidence-metrics"><div><dt>Pipeline processing</dt><dd>${h(m.timings?.total_seconds??'—')} seconds</dd></div><div><dt>Model/export allocations, peak</dt><dd>${h(m.peak_python_allocations_mb??'—')} MB</dd></div><div><dt>Loaded invoice lines</dt><dd>${h(m.warehouse_rows?.FactSales??'—')}</dd></div><div><dt>Publication gate</dt><dd>${h(m.publication_status||'Unknown')}</dd></div></dl><p>Runtime covers ${h(m.generation_mode||'this run')}. Memory measures traced model/export Python allocations, not total process RSS. These are single-run observations, not a scalability benchmark.</p><details><summary>Run identity and reproducibility</summary><pre>${h(JSON.stringify({seed:m.random_seed,data_through:m.data_through,generated:m.refreshed_at_utc,commit:m.commit,run:m.workflow_run,dependencies:m.dependencies,input_sha256:m.input_sha256},null,2))}</pre></details>`;
 const metrics=[['Positive inventory',money(f.positive_inventory_value)],['Negative-position adjustment',money(f.negative_inventory_value)],['Excess stock >90 days',money(f.excess_inventory_value)],['Overdue purchase value',money(f.overdue_po_value)],['Top 10 customer revenue share',`${((f.customer_top10_revenue_share||0)*100).toFixed(1)}%`],['On-time shipments',f.on_time_shipment_rate==null?'Unavailable':`${(f.on_time_shipment_rate*100).toFixed(1)}%`]];
 document.querySelector('#operating-evidence').innerHTML=`<h2>Operating exposure</h2><p>Full dataset · current-cost valuation · on-time means actual ship date ≤ requested ship date, among shipped orders.</p><div class="evidence-metrics">${metrics.map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('')}</div><details><summary>Open purchasing aging</summary><p>${Object.entries(f.po_aging||{}).map(([k,v])=>`${h(k)}: ${money(v)}`).join(' · ')}</p></details>`;
 const nodes=document.querySelectorAll('.data-table-card');const keys=['sales_by_category','customer_performance','inventory_detail','open_purchase_orders','vendor_performance','warehouse_performance','returns_by_reason','sales_detail'];
 nodes.forEach((box,i)=>{box.dataset.extract=keys[i];const c=data.extract_coverage?.[keys[i]];if(c)box.querySelector('.table-head').insertAdjacentHTML('afterend',`<p class="coverage-note">${h(c.selection)} · ${c.exported.toLocaleString()} of ${c.eligible.toLocaleString()} eligible records. ${h(c.scope)}.</p>`);box.querySelector('.csv-button').textContent='Download displayed extract'});
 // Domain-specific signal evidence is a separate, clearly scoped extract.
 for(const [key,investigation] of Object.entries(data.investigations||{})){
  const box=document.createElement('details');box.className='investigation';box.id=`investigation-${key}`;
  const columns=Object.keys(investigation.rows[0]||{});
  box.innerHTML=`<summary>Signal investigation · ${h(investigation.rule)}</summary><p>${investigation.exported} of ${investigation.total} matching records · full dataset. This is an investigation queue, not recovered revenue or cash.</p><div class="table-scroll"><table><thead><tr>${columns.map(c=>`<th>${h(c)}</th>`).join('')}</tr></thead><tbody>${investigation.rows.map(r=>`<tr>${columns.map(c=>`<td>${h(r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  document.querySelector(`#${key}`).appendChild(box);
 }
 document.querySelectorAll('.signal-card').forEach(a=>a.addEventListener('click',()=>{if(a.dataset.focus){const table=document.querySelector(`[data-extract="${a.hash==='#purchasing'?'vendor_performance':'warehouse_performance'}"]`);const input=table?.querySelector('input');if(input){input.value=a.dataset.focus;input.dispatchEvent(new Event('input'));requestAnimationFrame(()=>table.scrollIntoView({block:'start'}));return}}const key=a.hash.slice(1),target=document.querySelector(`#investigation-${key}`);if(target){target.open=true;requestAnimationFrame(()=>target.scrollIntoView({block:'start'}))}}));
 const revenue=Number(data.executive_kpis.revenue),exposure=Number(f.dead_inventory_value||0);
 const calculate=()=>{const bounded=(id,max)=>Math.min(max,Math.max(0,Number(document.querySelector(id).value)||0))/100;const reduction=bounded('#assumption-stock',100),carrying=bounded('#assumption-carry',100),margin=bounded('#assumption-margin',10);document.querySelector('#value-output').textContent=`Illustrative annual carrying-cost opportunity: ${money(exposure*reduction*carrying)}. Illustrative gross-profit opportunity on the full dataset's revenue: ${money(revenue*margin)}. Different time bases; do not add these into an ROI estimate.`};
 document.querySelector('#value-model').addEventListener('input',calculate);calculate();
}

function arrangeKpis(){
 const grid=document.querySelector('.kpi-grid');grid.insertBefore(document.querySelector('#gm-kpi').closest('.kpi'),document.querySelector('#orders').closest('.kpi'));
 const secondary=document.createElement('details');secondary.className='secondary-kpis';secondary.innerHTML='<summary>Customer, inventory, purchasing & additional comparison metrics</summary><div class="kpi-grid"></div>';
 for(const id of ['customers-kpi','inventory-kpi','po-value','yoy'])secondary.querySelector('.kpi-grid').appendChild(document.getElementById(id).closest('.kpi'));
 document.querySelector('#operating-evidence').before(secondary);
}
